import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased font-sans`}
      >
        <Toaster position="top-right" richColors />
        {children}
      </body>
    </html>
  );
}
